server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: dynastAdi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
paypal:
  client:
    id: Af6oKtRolAohHLszvg_8HtZwc5rn3EQ6QmOVUtBrkOHElNAAIghoBGRPafuu8aUtkn21ISnTXAJTygm_
    secret: EJmh5Hd32XOUUutOeRcBztWLQ10vm48I-lMdiG1tG6KXDNwg42Kt_inZ9dXVub1yrU3KQ8S6_d8C13R9
  base:
    url: https://api-m.sandbox.paypal.com